import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json=(status:number,body:unknown)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
type Lead={id:string;name:string|null;phone:string|null;email:string|null;channel:string|null;service_type:string|null;description:string|null;city:string|null;urgency:string|null;preferred_time:string|null;status:string|null;estimated_value_min:number|null;estimated_value_max:number|null};
type Analysis={priority:'low'|'normal'|'high'|'urgent';quality_score:number;qualification:'poor'|'possible'|'good'|'excellent';next_action:string;reply_draft:string;needs_appointment:boolean;needs_follow_up:boolean;summary:string};

function mockAnalysis(lead:Lead):Analysis{const hasContact=Boolean(lead.phone||lead.email);const value=Number(lead.estimated_value_max??lead.estimated_value_min??0);let score=45;if(hasContact)score+=20;if(lead.service_type)score+=10;if(lead.description)score+=8;if(lead.city)score+=5;if(value>=250)score+=10;if(lead.urgency==='high'||lead.urgency==='emergency')score+=7;score=Math.min(100,score);const qualification:Analysis['qualification']=score>=85?'excellent':score>=70?'good':score>=50?'possible':'poor';const priority:Analysis['priority']=lead.urgency==='emergency'?'urgent':lead.urgency==='high'?'high':score>=80?'high':score<50?'low':'normal';const service=lead.service_type||'de gevraagde dienst';const firstName=(lead.name||'klant').split(' ')[0];return{priority,quality_score:score,qualification,next_action:hasContact?`Neem contact op over ${service} en bevestig behoefte, timing en prijsindicatie.`:'Vraag eerst om een telefoonnummer of e-mailadres voordat je opvolgt.',reply_draft:`Hallo ${firstName}, bedankt voor je aanvraag over ${service}. We helpen je graag. Kun je bevestigen wanneer het voor jou het beste uitkomt? Dan plannen we de volgende stap meteen in.`,needs_appointment:Boolean(hasContact&&lead.preferred_time),needs_follow_up:hasContact,summary:`Lead beoordeeld op contactgegevens, dienst, urgentie, locatie en geschatte waarde. Score: ${score}/100.`};}

const responseSchema={type:'object',properties:{priority:{type:'string',enum:['low','normal','high','urgent']},quality_score:{type:'integer',minimum:0,maximum:100},qualification:{type:'string',enum:['poor','possible','good','excellent']},next_action:{type:'string'},reply_draft:{type:'string'},needs_appointment:{type:'boolean'},needs_follow_up:{type:'boolean'},summary:{type:'string'}},required:['priority','quality_score','qualification','next_action','reply_draft','needs_appointment','needs_follow_up','summary']};
async function geminiAnalysis(lead:Lead):Promise<{analysis:Analysis;model:string}>{const key=Deno.env.get('GEMINI_API_KEY')||Deno.env.get('GEIMINI_API_KEY');if(!key)throw new Error('Gemini API key is not configured');const model='gemini-2.5-flash-lite';const prompt=`Je bent de Lead2Job AI Revenue Agent voor Nederlandse servicebedrijven. Analyseer uitsluitend deze lead. Verzin geen ontbrekende feiten. Schrijf next_action, reply_draft en summary in natuurlijk Nederlands. Geef een praktisch verkoopadvies zonder iets automatisch naar de klant te sturen. Lead: ${JSON.stringify({name:lead.name,phone_present:Boolean(lead.phone),email_present:Boolean(lead.email),channel:lead.channel,service_type:lead.service_type,description:lead.description,city:lead.city,urgency:lead.urgency,preferred_time:lead.preferred_time,status:lead.status,estimated_value_min:lead.estimated_value_min,estimated_value_max:lead.estimated_value_max})}`;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:0.2,responseMimeType:'application/json',responseSchema}})});const p=await r.json();if(!r.ok)throw new Error(p?.error?.message||`Gemini request failed (${r.status})`);const text=p?.candidates?.[0]?.content?.parts?.[0]?.text;if(!text)throw new Error('Gemini returned no analysis');return{analysis:JSON.parse(text) as Analysis,model};}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json(405,{success:false,error:'Method not allowed'});try{const auth=req.headers.get('Authorization')||'';if(!auth.toLowerCase().startsWith('bearer '))return json(401,{success:false,error:'Missing authorization'});const url=Deno.env.get('SUPABASE_URL'),anon=Deno.env.get('SUPABASE_ANON_KEY');if(!url||!anon)return json(500,{success:false,error:'Server configuration incomplete'});const sb=createClient(url,anon,{global:{headers:{Authorization:auth}},auth:{persistSession:false}});const body=await req.json().catch(()=>({}));const leadId=typeof body?.lead_id==='string'?body.lead_id.trim():'';if(!leadId)return json(400,{success:false,error:'lead_id is required'});const {data:lead,error:leadError}=await sb.from('leads').select('id,name,phone,email,channel,service_type,description,city,urgency,preferred_time,status,estimated_value_min,estimated_value_max').eq('id',leadId).maybeSingle();if(leadError)return json(403,{success:false,error:'Could not load lead',detail:leadError.message});if(!lead)return json(404,{success:false,error:'Lead not found'});
let provider='gemini',model='gemini-2.5-flash-lite',providerError:string|null=null,analysis:Analysis;try{const result=await geminiAnalysis(lead as Lead);analysis=result.analysis;model=result.model;}catch(e){providerError=e instanceof Error?e.message:String(e);console.error('Gemini failed; using mock fallback',providerError);analysis=mockAnalysis(lead as Lead);provider='mock_fallback';model='lead2job-rules-v1';}
const {error:activityError}=await sb.from('activities').insert({lead_id:lead.id,type:'ai_analysis',channel:'ai',content:`AI analyse: ${analysis.qualification}, ${analysis.quality_score}/100. ${analysis.next_action}`,metadata:{provider,model,mode:'gemini_with_mock_fallback',provider_error:providerError,analysis}});if(activityError)return json(403,{success:false,error:'Analysis created but could not be saved',detail:activityError.message});return json(200,{success:true,provider,model,analysis,saved:true,provider_error:providerError});}catch(e){console.error('analyze-lead error',e);return json(500,{success:false,error:'Unexpected server error',detail:e instanceof Error?e.message:String(e)});}});